### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by muttmutt** [NorkzYT/BackupOnePass#14]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Does this issue exist in the latest version?

- [x] I am using the latest release

### Describe the bug?

It's me again!

I just upgraded to "latest" and now I'm getting the following error in the GUI and OnePassword closes when I click OK:

"1Password can't to open your saved data, however your data is still safe in your account. Contact support@1password.com for help."

### To Reproduce

Not sure, I did the upgrade from 1.0.5 -> 1.0.8.

### What OS are you seeing the problem on?

debian-12

### Expected behavior?

For it to work?

### Relevant log output

```shell
No logs I could find. Will post them if you tell me what to look for.
```

### Anything else?

Nope

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by muttmutt** [comment]
Here's the log from a manual run of entrypoint.sh.

[entrypoint.log](https://github.com/user-attachments/files/20047918/entrypoint.log)

**Comment by NorkzYT** [comment]
When you said `"Not sure, I did the upgrade from 1.0.5 -> 1.0.8."`. Are you talking about the docker image?
Since the latest version is `v1.0.6`.

I have also made some changes, run `make build-dev` after you clone the github repo.

**Comment by muttmutt** [comment]
Here's a big log file for you to play with. Here's my environment:

Linux plex 6.8.0-59-generic #61~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 17:03:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Docker version 28.1.1, build 4eba377
docker-compose/jammy,jammy,now 1.29.2-1 all [installed]

[logfile.txt.zip](https://github.com/user-attachments/files/20073380/logfile.txt.zip)

**Comment by NorkzYT** [comment]
@muttmutt 

Sometimes you need to read the logs to fix the issue. I immediately saw the `ERROR: BACKUP_SCHEDULE cannot be less frequent than every 2 minutes.` log right after `1Password launched successfully.` which caused the loop.

Ensure the environmental variable is the following or a higher number:
`BACKUP_SCHEDULE='*/2 * * * *'`

**Comment by muttmutt** [comment]
Yeah, I saw that but the schedule is set to ever 4 hours. Here's my redacted .env file:

```
BACKUP_ONE_PASS_USER='ubuntu'
BACKUP_ONE_PASS_PASSWORD='ubuntu'
BACKUP_ONE_PASS_GID='1000'
BACKUP_ONE_PASS_UID='1000'
BACKUP_ONE_PASS_TZ='America/Chicago'
**BACKUP_SCHEDULE='0 */4 * * *'**
BACKUP_ONE_PASS_ONEPASSWORD_EMAIL='phil.scarr@icloud.com'
BACKUP_ONE_PASS_ONEPASSWORD_SECRET_KEY='<key>'
BACKUP_ONE_PASS_ONEPASSWORD_PASSWORD='<password>'
BACKUP_ONE_PASS_ONEPASSWORD_TOTP_SECRET='<secred>'
BACKUP_ONE_PASS_VNC_PASSWORD='<password>'
DEBUG_MODE=true
COMPOSE_BAKE=true

```

**Comment by NorkzYT** [comment]
You have `DEBUG_MODE` set to true, thus the `docker-compose.dev.yml` will have the automation run right away. Check to see if your `.env` is not being read or in the same location as the docker compose file.

**Comment by muttmutt** [comment]
I take it back. The .dev version crashed too. This seems like it might be a problem?

backuponepass  | Error connecting: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)

**Comment by muttmutt** [comment]
My UID is 504 and not 1000, could that be causing problems?

**Comment by NorkzYT** [comment]
Your .env file looks fine. I will be checking the other issues later today. I will check on the public key change as well.

**Comment by muttmutt** [comment]
Cool, keep me posted. Until then, it’s manual mode for me…

--
Phil Scarr
***@***.***

🦋 Find me on Bluesky <https://bsky.app/profile/muttmutt.com>!

**Comment by NorkzYT** [comment]
@muttmutt 

I have pushed some changes. Please run `make build-dev`.

**Comment by muttmutt** [comment]
Nope, still failing.

[log.txt](https://github.com/user-attachments/files/20174259/log.txt)

**Comment by NorkzYT** [comment]
The logs have at least progressed. Checking the issue now.

**Comment by NorkzYT** [comment]
@muttmutt 

Run the same command again since it may stall. Thus time go into VNC and check to see what it is doing and the last thing that it does.

**Comment by NorkzYT** [comment]
Ah, I see what is going on.

**Comment by muttmutt** [comment]
Ok, here's the stuff.

<img width="1245" alt="Image" src="https://github.com/user-attachments/assets/25a27cf0-3718-4c96-bb23-4bc5a76f7133" />

[log2.txt](https://github.com/user-attachments/files/20174837/log2.txt)

**Comment by NorkzYT** [comment]
@muttmutt 

I have pushed new changes which has fixed the issue that I saw from your logs.

Run `make build-dev` again.

**Comment by muttmutt** [comment]
Nope, sorry. Stuck in the same place. I did do a git pull before rebuilding.

<img width="1123" alt="Image" src="https://github.com/user-attachments/assets/dde5c98d-9d79-40ba-b2f4-7fe3cc7c9716" />

[log3.txt](https://github.com/user-attachments/files/20175924/log3.txt)

**Comment by NorkzYT** [comment]
Rebuild 1 more time. This time there is no need to send logs or a screenshot. Only check if it says `"Timeout reached waiting for account sync."`.

**Comment by NorkzYT** [comment]
@muttmutt ^.

**Comment by muttmutt** [comment]
Here you go:

Attempting to find button using template: /backuponepass/images/button_template_white.png
Taking a screenshot...
Template matched. Finding the best match.
Button found at (475, 166).
Moving to coordinates: (475, 166)
Clicking at coordinates: (475, 166)
Initial button clicked. Waiting for UI animation...
Waiting for account sync to complete...
Timeout reached waiting for account sync.

And the container exits.

Just to be sure, I did a make clean and then a make build-dev. Same result. I also tried going back to UID 1000 but it made no difference. I need it to work with 504, but I'll improvise if needed.

**Comment by NorkzYT** [comment]
@muttmutt 

May I know why do you need it to work with UID `504`?

This is my `.env`:
```env
BACKUP_ONE_PASS_USER='onepassword'
BACKUP_ONE_PASS_PASSWORD='onepassword'
BACKUP_ONE_PASS_GID='1000'
BACKUP_ONE_PASS_UID='1000'
BACKUP_ONE_PASS_TZ='America/New_York'
BACKUP_SCHEDULE='*/2 * * * *'
BACKUP_ONE_PASS_ONEPASSWORD_EMAIL='your_email@example.com'
BACKUP_ONE_PASS_ONEPASSWORD_SECRET_KEY='your_secret_key'
BACKUP_ONE_PASS_ONEPASSWORD_PASSWORD='your_password'
BACKUP_ONE_PASS_ONEPASSWORD_TOTP_SECRET='your_TOTP_secret'
BACKUP_ONE_PASS_VNC_PASSWORD='xxx'
COMPOSE_BAKE=true
DEBUG_MODE=true
```

I believe the  `"Timeout reached waiting for account sync."` log is occurring since it may not be picking up the `BACKUP_ONE_PASS_USER` for some reason.

**Comment by muttmutt** [comment]
It’s the UID of my account from way, way, WAY back in the day (When UNIX was UNIX and Windows was a grapphical shell on top of DOS).

But I can use the GID 1000 and make it work. So no problem.

You shouldn’t assume that every user is going to be UID 1000…. 😜

--
Phil Scarr
***@***.***

🦋 Find me on Bluesky <https://bsky.app/profile/muttmutt.com>!

**Comment by NorkzYT** [comment]
@muttmutt 

I understand what you have said. This is a docker container and perhaps you have not understood that the UID and GUID is set for the user in the docker container.

As shown in the code below:

https://github.com/NorkzYT/BackupOnePass/blob/2224ee13f19e79edaafa1a9da5b0eda3fc94a29f/docker/config/entrypoint.sh#L17-L21

It is not meant for any user in you system that docker is being ran in.

I am going to hard code it instead of leaving it dynamic with the use of:
```env
BACKUP_ONE_PASS_GID='1000'
BACKUP_ONE_PASS_UID='1000'
```

As the value does not need to be changed.

**Comment by muttmutt** [comment]
Oh, I understand the whole container thing, but when it writes files onto the host filesystem, it uses that UID and GID.

QOXA63A-20250503-013034.1pux
-rw------- 1 1000 1000 12804041 May  3 07:30 1PasswordExport-JIJ6ZQLTAZESLHQBCEHQOXA63A-20250503-073034.1pux
-rw------- 1 1000 1000 12804249 May  3 13:30 1PasswordExport-JIJ6ZQLTAZESLHQBCEHQOXA63A-20250503-133034.1pux
-rw------- 1 1000 1000 12804443 May  3 19:30 1PasswordExport-JIJ6ZQLTAZESLHQBCEHQOXA63A-20250503-193035.1pux
-rw------- 1 1000 1000 12804999 May  4 01:30 1PasswordExport-JIJ6ZQLTAZESLHQBCEHQOXA63A-20250504-013032.1pux
-rw------- 1 1000 1000 12804137 May  4 07:30 1PasswordExport-JIJ6ZQLTAZESLHQBCEHQOXA63A-20250504-073032.1pux
-rw------- 1 1000 1000 12803512 May  4 13:30 1PasswordExport-JIJ6ZQLTAZESLHQBCEHQOXA63A-20250504-133032.1pux
-rw------- 1 1000 1000 12804314 May  4 19:30 1PasswordExport-JIJ6ZQLTAZESLHQBCEHQOXA63A-20250504-193033.1pux
-rw------- 1 1000 1000 12802960 May  5 01:30 1PasswordExport-JIJ6ZQLTAZESLHQBCEHQOXA63A-20250505-013035.1pux
-rw------- 1 1000 1000 12804183 May  5 07:30 1PasswordExport-JIJ6ZQLTAZESLHQBCEHQOXA63A-20250505-073034.1pux


and t will need to work around that by periodically changing the file permissions to 660.

--
Phil Scarr
***@***.***

🦋 Find me on Bluesky <https://bsky.app/profile/muttmutt.com>!

**Comment by NorkzYT** [comment]
Ah, I understand. Will work on that then to have the files permission be 660.

**Comment by NorkzYT** [comment]
@muttmutt 

Done. I have pushed the new changes.

https://github.com/NorkzYT/BackupOnePass/blob/230a0e0ffc3cae3aeb6fabcede7ae7c848caf3c1/.env.example#L1-L11

https://github.com/NorkzYT/BackupOnePass/blob/230a0e0ffc3cae3aeb6fabcede7ae7c848caf3c1/docker/1password_cron.sh#L39-L40

**Comment by muttmutt** [comment]
I wish I had better news... ¯\_(ツ)_/¯


<img width="1120" alt="Image" src="https://github.com/user-attachments/assets/584df494-e4bd-46a3-a84c-db5692c0ce17" />

[log4.txt](https://github.com/user-attachments/files/20178104/log4.txt)

**Comment by NorkzYT** [comment]
@muttmutt 

I will keep working on it tomorrow. Good night.

**Comment by NorkzYT** [comment]
> I wish I had better news... ¯_(ツ)_/¯
> 
> <img alt="Image" width="1120" src="https://private-user-images.githubusercontent.com/46875832/442973749-584df494-e4bd-46a3-a84c-db5692c0ce17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDcxNTE4MjAsIm5iZiI6MTc0NzE1MTUyMCwicGF0aCI6Ii80Njg3NTgzMi80NDI5NzM3NDktNTg0ZGY0OTQtZTRiZC00NmEzLWE4NGMtZGI1NjkyYzBjZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTEzVDE1NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzI4ODc1MDRlNzc5ZGU2MmU5ODlmZDU4N2VlODhjY2IxY2ZkYzM0ZWZkZTY5MDVlYzAxZjE1YWNmZGUzNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s9A13OXhQuTjpKYTQu4yQhj9-8RpqeqjAuCnOv4hV6Q">
> [log4.txt](https://github.com/user-attachments/files/20178104/log4.txt)

@muttmutt 

From the above image you sent it looks like you are on an old 1Password version since I do not have that UI format which means you have been re-building a build-cache.
This is the reason why the automation is not working since there is no code to handle that old 1Password UI that asks "How do you want to authenticate?".

Unless this is an account based function then I do not need to add code to add a use case for this, else I will update the code to make sure it supports it as well.

Thus run the following. The system will prompt you for input and let you know what it does before it runs. (If you do not know what it does already).

`docker system prune -a`.

Then run `make build-dev`.

**Comment by NorkzYT** [comment]
If you still receive the same issue then please send me a screenshot of only the following text as an example:

![Image](https://github.com/user-attachments/assets/a620c41f-aa89-44b1-9a86-cb984314e89c)

As I will need to have the code check if the check is existent first to handle it. Here is the one image that is checked to handle 2FA:
![backuponepass_2fa_text](https://github.com/NorkzYT/BackupOnePass/blob/main/docker/images/backuponepass_2fa_text.png?raw=true)

**Comment by muttmutt** [comment]
I did the prune and rebuild with the same result. Sorry.

--
Phil Scarr
***@***.***

🦋 Find me on Bluesky <https://bsky.app/profile/muttmutt.com>!

**Comment by muttmutt** [comment]
Not sure if this is what you want but here you go:

￼

From this dialog:


￼


--
Phil Scarr
***@***.***

🦋 Find me on Bluesky <https://bsky.app/profile/muttmutt.com>!

**Comment by NorkzYT** [comment]
@muttmutt 

You need to go in this GitHub issue instead of answering from email and send the screenshot by pasting it and then sending the comment as the following is what I can see:

![Image](https://github.com/user-attachments/assets/5729f721-c320-46b3-b55a-ca0783b92e19)

**Comment by muttmutt** [comment]
Oops, sorry about that. Here you go!

<img width="186" alt="Image" src="https://github.com/user-attachments/assets/d955faab-610f-4187-a50c-640be288b29b" />

<img width="127" alt="Image" src="https://github.com/user-attachments/assets/8aa72b10-ecef-4d20-bbdd-507b152af572" />

**Comment by NorkzYT** [comment]
No problem. Thank you, will see if that works as the only part I needed was the "How do you want to authenticate?" part. I can crop it.

**Comment by NorkzYT** [comment]
@muttmutt 

I have pushed changes. Hopefully the image is clear enough that the automation catches it and does not fail.
This time open VNC and see the logs in the container as well to know what is going on.

**Comment by NorkzYT** [comment]
One sec. I added a wrong line.

**Comment by muttmutt** [comment]
I pulled the updates and rebuilt the container, same result. Sorry.

**Comment by muttmutt** [comment]
Sorry, here you go.

[log6.txt](https://github.com/user-attachments/files/20195472/log6.txt)

**Comment by NorkzYT** [comment]
@muttmutt 

Made changes. Try again.

**Comment by NorkzYT** [comment]
@muttmutt^

Bumping this.

**Comment by muttmutt** [comment]
I pulled the latest and am trying again.
--
Phil Scarr
***@***.***

🦋 Find me on Bluesky <https://bsky.app/profile/muttmutt.com>!

**Comment by NorkzYT** [comment]
@muttmutt^

Bumping this. Any updates?
Also no rush. This is only for a reminder.

**Comment by muttmutt** [comment]
> [@muttmutt](https://github.com/muttmutt)^
> 
> Bumping this. Any updates? Also no rush. This is only for a reminder.

Yeah, so I cloned a fresh copy and tried again, it still doesn't work but neither does VNC / webVNC, even in the dev environment. There are numerous DBus errors in the log so I'm not sure what that's all about.  Attached is the log from the latest attempts. The first is from a dev build and the 2nd from a prod build.

[log1.txt](https://github.com/user-attachments/files/20258714/log1.txt)
[log2.txt](https://github.com/user-attachments/files/20258713/log2.txt)

**Comment by NorkzYT** [comment]
@muttmutt 

Run a git pull first since you are on 1 old commit that broke the VNC.

**Comment by muttmutt** [comment]
I did a new git clone and a new build-dev, same result. Not sure where I’m going wrong...
--
Phil Scarr
***@***.***

🦋 Find me on Bluesky <https://bsky.app/profile/muttmutt.com>!

**Comment by muttmutt** [comment]
Sorry, not a good weekend for me to do this. I’ll check with you next week.
--
Phil Scarr
***@***.***

🦋 Find me on Bluesky <https://bsky.app/profile/muttmutt.com>!

**Comment by NorkzYT** [comment]
@muttmutt 

No problem. Whenever you are available.

**Comment by muttmutt** [comment]
What timezone are you in? I’m in US CDT (UTC -5:00).
--
Phil Scarr
***@***.***

🦋 Find me on Bluesky <https://bsky.app/profile/muttmutt.com>!

**Comment by NorkzYT** [comment]
@muttmutt 

I am in EST (UTC -4:00).
